(load "cell.lisp")
(load "nanorobot.lisp")

(defun new-nanorobot ()
  (let ((energy 100))
    #'(lambda (cell)
        (cond ((and (cell-cancer-p cell) (> energy 10))
                (decf energy 10)
                'ATTACK)
              ((and (< energy 10) (cell-red-p cell))
               (setf energy 100)
                'RECHARGE)
              ((< energy 10)
               (decf energy 1)
                'STAY)
              (T 'WAIT)
        )
      )
  )
)
