(defun new-nanorobot ()
  (let ((energy 100))
    #'(lambda (nr)
        (when (nr-cancer nr)
          (decf energy 10))
        (cond ((and (nr-cancer nr) (> energy 10))
                'ATTACK)
              ((and (< energy 10) (nr-red-globule nr))
                'RECHARGE)
              ((< energy 10)
                'STAY
              (T 'WAIT))
        )
      )
  )
)
